version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ../.sql:/docker-entrypoint-initdb.d
